// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pcms.Models;

namespace pcms.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pcms.Models.Employee", b =>
                {
                    b.Property<long>("sk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("add_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("add_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("chg_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("chg_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("emr_cnt")
                        .HasColumnType("int");

                    b.Property<string>("yr_mon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sk");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
